#define TASKTEXT1 QObject::tr("Change #ARTIST via ID3 tag from audio file")
#define TASKTEXT2 QObject::tr("Change #TITLE via ID3 tag from audio file")
#define TASKTEXT3 QObject::tr("Change #TITLE via ID3 tag from audio file, append \"[VIDEO]\" if video present")
#define TASKTEXT4 QObject::tr("Change #TITLE, append \"[VIDEO]\" if video present")
#define TASKTEXT5 QObject::tr("Do not use ID3 tag information.")
#define TASKTEXT6 QObject::tr("Change #TITLE, remove [...] tags")
#define TASKTEXT7 QObject::tr("Do not use ID3 tag information.")
#define TASKTEXT8 QObject::tr("Change #TITLE, append \"[KARAOKE]\" if song is karaoke")
#define TASKTEXT9 QObject::tr("Change #GENRE via ID3 tag")
#define TASKTEXT10 QObject::tr("Change #YEAR via ID3 tag")
#define TASKTEXT11 QObject::tr("Change #ALBUM via ID3 tag")
#define TASKTEXT12 QObject::tr("You need the custom tag #ALBUM for this task.")
#define TASKTEXT13 QObject::tr("Write #BACKGROUND even without existing image file")
