#define TASKTEXT1 tr("Change path to \"Artist - Title\" (default)")
#define TASKTEXT2 tr("All songs will be in the UltraStar song folder with a custom subdirectory for each one.")
#define TASKTEXT3 tr("Change path to \"Genre/Artist - Title\"")
#define TASKTEXT4 tr("Songs will be organized in subdirectories by their genres.")
#define TASKTEXT5 tr("Change path to \"Edition/Artist - Title\"")
#define TASKTEXT6 tr("Songs will be organized in subdirectories by their edition.")
#define TASKTEXT7 tr("Change path to \"Artist/Artist - Title\"")
#define TASKTEXT8 tr("Songs will be organized in subdirectories by their artist.")
#define TASKTEXT9 tr("Change path to \"Language/Artist - Title\"")
#define TASKTEXT10 tr("Songs will be organized in subdirectories by their language.")
#define TASKTEXT11 tr("Change path to \"Artist/Album/Artist - Title\"")
#define TASKTEXT12 tr("Songs will be organized in subdirectories by their artist and album.<br><b>You need the custom tag #ALBUM for this task.</b>")
#define TASKTEXT13 tr("Rename directory to \"Artist - Title\"")
#define TASKTEXT14 tr("Rename directory to \"Artist - Title [VIDEO] [SC]\" if checked or video present. Keep other folder tags.")
#define TASKTEXT15 tr("Looks for <b>[SC]</b> in the <b>#EDITION</b> tag to find out whether it is checked or not.<br><br>Other folder tags like <b>[KARAOKE]</b> will be appended to the end if present.")
#define TASKTEXT16 tr("Rename songtext file to \"Artist - Title.txt\"")
#define TASKTEXT17 tr("Rename audio file to \"Artist - Title.*\"")
#define TASKTEXT18 tr("Rename cover to \"Artist - Title [CO].*\"")
#define TASKTEXT19 tr("Rename the cover file to a proper schema.<br>File endings will be preserved.")
#define TASKTEXT20 tr("Rename background to \"Artist - Title [BG].*\"")
#define TASKTEXT21 tr("Rename video to \"Artist - Title.*\"")
#define TASKTEXT22 tr("Rename video to \"Artist - Title [VD#*].*\" consider VIDEOGAP")
#define TASKTEXT23 tr("Uses <b>#VIDEOGAP:0</b> if tag not present.")
#define TASKTEXT24 tr("Change #ARTIST via ID3 tag from audio file.")
#define TASKTEXT25 tr("Change #TITLE via ID3 tag from audio file.")
#define TASKTEXT26 tr("Change #TITLE via ID3 tag from audio file. Append \"[VIDEO]\" if video present.")
#define TASKTEXT27 tr("Change #TITLE. Append \"[VIDEO]\" if video present.")
#define TASKTEXT28 tr("Do not use ID3 tag information.")
#define TASKTEXT29 tr("Change #TITLE. Remove [...]-Tags.")
#define TASKTEXT30 tr("Do not use ID3 tag information.")
#define TASKTEXT31 tr("Change #GENRE via ID3 tag.")
#define TASKTEXT32 tr("Change #YEAR via ID3 tag.")
#define TASKTEXT33 tr("Change #ALBUM via ID3 tag")
#define TASKTEXT34 tr("You need the custom tag #ALBUM for this task.")
