#define TASKTEXT1 QObject::tr("Change path to \"Artist - Title\" (default)")
#define TASKTEXT2 QObject::tr("All songs will be in the UltraStar song folder with a custom subdirectory for each one.")
#define TASKTEXT3 QObject::tr("Change path to \"Genre/Artist - Title\"")
#define TASKTEXT4 QObject::tr("Songs will be organized in subdirectories by their genres.")
#define TASKTEXT5 QObject::tr("Change path to \"Edition/Artist - Title\"")
#define TASKTEXT6 QObject::tr("Songs will be organized in subdirectories by their edition.")
#define TASKTEXT7 QObject::tr("Change path to \"Artist/Artist - Title\"")
#define TASKTEXT8 QObject::tr("Songs will be organized in subdirectories by their artist.")
#define TASKTEXT9 QObject::tr("Change path to \"Language/Artist - Title\"")
#define TASKTEXT10 QObject::tr("Songs will be organized in subdirectories by their language.")
#define TASKTEXT11 QObject::tr("Change path to \"Artist/Album/Artist - Title\"")
#define TASKTEXT12 QObject::tr("Songs will be organized in subdirectories by their artist and album.<br><b>You need the custom tag #ALBUM for this task.</b>")
#define TASKTEXT13 QObject::tr("Rename directory to \"Artist - Title\"")
#define TASKTEXT14 QObject::tr("Rename directory to \"Artist - Title [VIDEO] [SC]\" if checked or video present. Keep other folder tags.")
#define TASKTEXT15 QObject::tr("Looks for <b>[SC]</b> in the <b>#EDITION</b> tag to find out whether it is checked or not.<br><br>Other folder tags like <b>[KARAOKE]</b> will be appended to the end if present.")
#define TASKTEXT16 QObject::tr("Rename songtext file to \"Artist - Title.txt\"")
#define TASKTEXT17 QObject::tr("Rename audio file to \"Artist - Title.*\"")
#define TASKTEXT18 QObject::tr("Rename cover to \"Artist - Title [CO].*\"")
#define TASKTEXT19 QObject::tr("Rename the cover file to a proper schema.<br>File endings will be preserved.")
#define TASKTEXT20 QObject::tr("Rename background to \"Artist - Title [BG].*\"")
#define TASKTEXT21 QObject::tr("Rename video to \"Artist - Title.*\"")
#define TASKTEXT22 QObject::tr("Rename video to \"Artist - Title [VD#*].*\" consider VIDEOGAP")
#define TASKTEXT23 QObject::tr("Uses <b>#VIDEOGAP:0</b> if tag not present.")
